# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Priority',
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Priority', 'verbose_name_plural': 'Priorities'},
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='due_date',
        ),
        migrations.AddField(
            model_name='todolist',
            name='priority',
            field=models.ForeignKey(default='normal', on_delete=django.db.models.deletion.CASCADE, to='todolist.Priority'),
        ),
    ]
