# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20180917_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.ForeignKey(default='Normal', on_delete=django.db.models.deletion.CASCADE, to='todolist.Priority'),
        ),
    ]
