# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20180917_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='state',
            field=models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.CASCADE, to='todolist.State'),
        ),
    ]
